production:
  solr:
    min_memory: 30M
    max_memory: 100M
    hostname: localhost
    port: 8983
    log_level: WARNING

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: DEBUG

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
